### ISSUE TITLE
Tab doesn't indent

### ISSUE THREAD

**Issue by akashenfelter** [whizzml/whizzml-mode#2]
When I hit tab I get the error `*ERROR*: Symbol's function definition is void: string-trim`. I think my issue is similar to the one at the link; when I added `(require 'subr-x)` it went away.

https://github.com/alphapapa/org-protocol-capture-html/issues/7

**Comment by jaor** [comment]
oh, good catch! i pushed a patch that should fix the problem: please let me know if it works for you. thanks!

**Comment by akashenfelter** [comment]
Strangely, this doesn't seem to fix the issue. But if I add the line to my init.el, it's fine.

**Comment by jaor** [comment]
> Strangely, this doesn't seem to fix the issue. But if I add the line
> to my init.el, it's fine.

hmmm.  did you reload the file after applying the change? just requiring
it again won't help...

**Comment by akashenfelter** [comment]
I made the change, closed emacs, opened it back up again, and loaded the file. Could it be because I keep whizzml-mode.el in a subdirectory?

**Comment by jaor** [comment]
i take it "i made the change" means you merged the new version of
whizzml-mode from this repo, right?  and then, without requiring
explicitly subr-x in your init.el, things don't work after loading
whizzml-mode.el, right?

how do you load whizzml-mode.el? (no, it doesn't matter where the files
live, as long as it is loaded)

**Comment by akashenfelter** [comment]
I'm so sorry, I actually just manually added the `(require 'subr-x)` to whizzml-mode.el. I see now that was the wrong thing to do. When I clone this repo and copy whizzml-mode.el to the appropriate directory, everything works beautifully.
