### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by charleslparker** [whizzml/whizzml-mode#4]
1. When creating a map literal I get this behavior:

```
(define x {"a" 1
           "b" 2
"c" 3
```

So hitting return after the first kv-pair indents properly, but after the second it jumps back to the beginning of the line.

2. Indentation on `if` statements seems to line up the condition and the consequents:

```
(if (empty? x)
    (count y)
    (count x))
```

I expected two spaces under the if rather than four.  Is this intended?

**Comment by charleslparker** [comment]
FYI it looks like the same thing is happening with 3 or more bindings in a `let`

**Comment by jaor** [comment]
yes, i've been procrastinating over these problems for a while :).  thanks, charlie, i'll take a look!

**Comment by jaor** [comment]
@charleslparker i've added a couple commits that should fix this issue... let me know if it works for you, thanks!

**Comment by charleslparker** [comment]
This fixes map literals for me but there's still a problem with `let` bindings and `if`.  For example

```
(define (test x)
  (let (y 1
          _  ;;hitting return after the line ending in 1 causes the cursor to appear under the 1 instead of the y
```
Similarly, if I have two bindings in a let that are properly aligned, hitting return at the end of the second binding "corrects" my indentation by moving it under the the second form of the first binding as above.

Finally, hitting return after the test in an `if` puts the cursor under the test rather than two spaces in from the opening paren.

Obviously, none of this is even close to a big deal.

**Comment by charleslparker** [comment]
Wait, never mind!  For some reason I got switched to scheme-mode.  Hold on.

**Comment by charleslparker** [comment]
Yes, everything is awesome now, indentation-wise!
